config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  get '/users/sign_up', to: 'registrations#new', as: 'registration'
  post '/users' , to: 'registrations#create'

  get '/user/sign_in' , to: 'sessions#new', as:'session'
  post '/login' , to: 'sessions#create', as:'login'

  delete '/users/sign_out' , to: 'sessions#destroy', as:'logout'

  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :book, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true , format: { with: /[\w]+@([\w-]+\.)+[\w-]{2,4}/ }
  validates :password, presence: true, confirmation: true
  validates :nickname, presence: true

  before_create :encrypt_password

  def self.login(user)
    pw = Digest::SHA1.hexdigest("a#{user[:password]}z")
    User.find_by(email: user[:email], password: pw)
  end



  private
  def encrypt_password
    self.password = Digest::SHA1.hexdigest("a#{self.password}z")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(clean_book)
    if @book.save
      redirect_to root_path, notice:'新增成功'
    else
      render :new
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(clean_book) 
      redirect_to root_path, notice:'編輯成功'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to root_path, notice:'刪除成功'
  end

  private
  def clean_book
    params.require(:book).permit(:name, :author, :price, :comment)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: 'OK!'
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :nickname)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if User.login(params[:user])
      session[:user9527] = params[:user][:email]
      redirect_to root_path, notice:'登入成功'
    else
      redirect_to sessions_path, notice:'登入失敗'
    end
  end

  def destroy
    session[:user9527] = nil
    redirect_to root_path, notice:'已登出'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user9527].present?
      User.find_by(email: session[:user9527])
    else
      nil
    end
  end
end

app/views/books/edit.html.erb
<h1>編輯書籍</h1>

<% if @book.errors.any? %>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@book) do |form| %>

<div>
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>
<div>
  <%= form.label :author %>
  <%= form.text_field :author %>
</div>
<div>
  <%= form.label :comment %>
  <%= form.text_area :comment %>
</div>
<div>
  <%= form.submit '送出' %>
</div>

<% end %>

app/views/books/index.html.erb
<h1>書籍列表</h1>


<%= flash[:notice] %>

<%= link_to '新增書籍' , new_book_path %>


<table>
    <tr>
      <td>name</td>
      <td>author</td>
    </tr>

  <% @books.each do |book| %>
    <tr>
      <td><%= link_to book.name , book_path(book.id) %></td>
      <td><%= book.author %></td>
      <td><%= link_to '編輯' , edit_book_path(book.id) %></td>
      <td><%= link_to '刪除' , book_path(book.id), method: 'delete' %></td>
    </tr>
  <% end %>
</table>


<% if current_user %>
  <%= current_user.nickname %>
  <%= link_to '登出', logout_path, method:'delete' %>
<% else %>
  <%= link_to '註冊', registration_path %>
  <%= link_to '登入', session_path %>
<% end %>

app/views/books/new.html.erb
<h1>請填表格並新增</h1>

<% if @book.errors.any? %>
  <ul>
    <%= @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@book) do |form| %>

<div>
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>

<div>
  <%= form.label :author %>
  <%= form.text_field :author %>
</div>

<div>
  <%= form.label :comment %>
  <%= form.text_area :comment %>
</div>

<div>
  <%= form.submit '送出' %>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sellboo05</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>